version: "3"
services:
  my-datascience-notebook:
    image: jupyter/datascience-notebook:python-3.9.7
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
    command: start-notebook.sh --NotebookApp.token=''
